name: update-neovim-nightly
run-name: Check for updates/Update neovim-nightly package

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Get release id
        id: release_info
        run: |
          release=$(curl -sL https://api.github.com/repos/neovim/neovim/releases/tags/nightly)
          release_id=$(echo "$release" | jq -r ".id")
          release_html_url=$(echo "$release" | jq -r ".html_url")
          echo "release_id=${release_id}" >> $GITHUB_OUTPUT
          echo "release_html_url=${release_html_url}" >> $GITHUB_OUTPUT

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Get ebuild id
        id: ebuild_info
        run: |
          cd app-editors/neovim-nightly
          ebuild_name=$(find neovim-nightly*.ebuild | head -n 1)
          ebuild_id=$(echo "${ebuild_name%.ebuild}" | cut -d '-' -f 3)
          echo "ebuild_id=${ebuild_id}" >> $GITHUB_OUTPUT

      - name: Rename ebuild to new id
        if: steps.release_info.outputs.release_id != steps.ebuild_info.outputs.ebuild_id
        env:
          RELEASE_ID: ${{ steps.release_info.outputs.release_id }}
          EBUILD_ID: ${{ steps.ebuild_info.outputs.ebuild_id }}
        run: |
          cd app-editors/neovim-nightly
          mv neovim-nightly-${EBUILD_ID}.ebuild neovim-nightly-${RELEASE_ID}.ebuild

      - name: Commit changes
        if: steps.release_info.outputs.release_id != steps.ebuild_info.outputs.ebuild_id
        uses: EndBug/add-and-commit@v9
        with:
          message: Update neovim-nightly package
          default_author: user_info
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
